services:
  frontend-dev:
    profiles: ["dev"]
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend-prod:
    profiles: ["prod"]
    build:
      context: .
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
